<a href="https://colab.research.google.com/github/wiuver/tipis/blob/main/itz8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лабораторная работа 8. Применение нейросетей для распознавания образов

In [ ]:
import cv2
from google.colab import drive
from google.colab.patches import cv2_imshow
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import to_categorical
import keras

In [ ]:

alph = ['A','Б','В','Г','Д','Е','Ж','З'] # набор букв

# Загружаем изображения 5×7 пикселей
img = []
for a in alph:
    im = cv2.imread('/content/' + a + '.png', cv2.IMREAD_GRAYSCALE)
    img.append(im)

# Готовим X (входы)
X = []
for im in img:
    vec = im.reshape(-1)          # векторизация
    vec = np.where(vec == 0, 1, 0)
    X.append(vec)

X = np.array(X)

# Готовим y (метки)
y_int = np.arange(len(alph))
y = to_categorical(y_int, num_classes=8)

# Создаём модель softmax-классификации
model = Sequential()
model.add(Dense(64, input_shape=(X.shape[1],), activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(8, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Обучение
model.fit(X, y, epochs=300, verbose=1)



Epoch 1/300


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 861ms/step - accuracy: 0.0000e+00 - loss: 2.1063
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.0000e+00 - loss: 2.0685
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.0000e+00 - loss: 2.0333
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.0000e+00 - loss: 2.0022
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.0000e+00 - loss: 1.9735
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2500 - loss: 1.9456
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.3750 - loss: 1.9188
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.3750 - loss: 1.8944
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.3750 - loss: 1.8712
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 1.8484
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 1.8262
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.

In [ ]:
def predict_letter(path):
    im = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    print(im)
    vec = im.reshape(-1)
    vec = np.where(vec == 0, 1, 0)
    vec = vec.reshape(1, -1)

    pred = model.predict(vec)
    idx = np.argmax(pred)

    return alph[idx]

# Буква А
letter = predict_letter('/content/A.png')
print("Буква:", letter)

# Буква Г
letter = predict_letter('/content/Г.png')
print("Буква:", letter)

# Буква Ж
letter = predict_letter('/content/Ж.png')
print("Буква:", letter)

# Буква Г с шумом
letter = predict_letter('/content/Г_ШУМ.png')
print("Буква:", letter)

# Буква А с шумом
letter = predict_letter('/content/А_ШУМ.png')
print("Буква:", letter)

# Буква Д с шумом
letter = predict_letter('/content/Д_ШУМ.png')
print("Буква:", letter)

[[255   0   0   0 255]
 [  0 255 255 255   0]
 [  0 255 255 255   0]
 [  0 255 255 255   0]
 [  0   0   0   0   0]
 [  0 255 255 255   0]
 [  0 255 255 255   0]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Буква: A
[[  0   0   0   0   0]
 [  0 255 255 255 255]
 [  0 255 255 255 255]
 [  0 255 255 255 255]
 [  0 255 255 255 255]
 [  0 255 255 255 255]
 [  0 255 255 255 255]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
Буква: Г
[[  0 255   0 255   0]
 [  0 255   0 255   0]
 [  0 255   0 255   0]
 [255   0   0   0 255]
 [  0 255   0 255   0]
 [  0 255   0 255   0]
 [  0 255   0 255   0]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
Буква: Ж
[[  0   0   0   0   0]
 [  0 255 255 255 255]
 [  0 255   0 255   0]
 [  0 255 255 255 255]
 [  0   0 255 255 255]
 [  0 255   0 255 255]
 [  0 255 255 255 255]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Буква: Г
[[255   0   0   0 255]
 [  0 255 255 255   0]
 [  0   0 255 255   0]
 [  0 255 255 255   0]
 [  0   0   0   0   0]
 [  0 255 255 255   0]
 [  0 255 255   0   0]]
1/